# Generated by Django 4.1.1 on 2022-10-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='address',
            field=models.CharField(default='exit', max_length=500, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giftcard',
            name='metro',
            field=models.CharField(default='exit', max_length=255, verbose_name='Метро'),
            preserve_default=False,
        ),
    ]
